import type { Metadata } from "next";
import { IBM_Plex_Sans } from 'next/font/google';
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'], // шаардлагатай жингүүдээ сонгоно
  style: ['normal'], // эсвэл 'italic' нэмэж болно
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


export const metadata: Metadata = {
  title: "NewsGo - Blog web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={ibmPlexSans.className}
      >
        {children}
      </body>
    </html>
  );
}
